config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :military_rank_tests
  devise_for :users
  resources :users

  get '/roulette_wheel_consecutive_count' => 'pages#roulette_wheel_consecutive_count'
  get '/rock_paper_scissors'              => 'pages#rock_paper_scissors'
  get '/tick_tack_toe'                    => 'pages#tick_tack_toe'
  get '/random_quote'                     => 'pages#random_quote'
  get '/quick_check'                      => 'pages#quick_check'
  get '/jockoclock'                       => 'pages#jockoclock'
  get '/calculator'                       => 'pages#calculator'
  get '/scratch'                          => 'pages#scratch'
  get '/heart'                            => 'pages#heart'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/military_rank_test.rb
class MilitaryRankTest < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :military_rank_tests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/military_rank_tests_controller.rb
class MilitaryRankTestsController < ApplicationController
  before_action :set_military_rank_test, only: [:show, :edit, :update, :destroy]

  def index
    @military_rank_tests = MilitaryRankTest.all
  end

  def show
  end

  def new
    if current_user.nil?
      redirect_to new_user_path
    end

    @military_rank_test = MilitaryRankTest.new
  end

  def edit
  end

  def create
    @military_rank_test = MilitaryRankTest.new
    @military_rank_test.user = current_user

    10.times do |x|
      @question = Question.new
      @question.save
      @military_rank_test.questions << @question
    end

    respond_to do |format|
      if @military_rank_test.save
        format.html { redirect_to @military_rank_test, notice: 'Military rank test was successfully created.' }
        format.json { render :show, status: :created, location: @military_rank_test }
      else
        format.html { render :new }
        format.json { render json: @military_rank_test.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @military_rank_test.update(military_rank_test_params)
        format.html { redirect_to @military_rank_test, notice: 'Military rank test was successfully updated.' }
        format.json { render :show, status: :ok, location: @military_rank_test }
      else
        format.html { render :edit }
        format.json { render json: @military_rank_test.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @military_rank_test.destroy
    respond_to do |format|
      format.html { redirect_to military_rank_tests_url, notice: 'Military rank test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_military_rank_test
      @military_rank_test = MilitaryRankTest.find(params[:id])
    end

    def military_rank_test_params
      params.require(:military_rank_test).permit(:branch)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def calculator
  end

  def heart
  end

  def index
  end

  def jockoclock
  end

  def quick_check
  end

  def random_quote
  end

  def roulette_wheel_consecutive_count
  end

  def tick_tack_toe
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:string, :string, :string, :string, :string, :string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/military_rank_tests_helper.rb
module MilitaryRankTestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def return_home_button
    %(
      <div class='row'>
        <div class='col-6 offset-3'>
          <a href="/" class="btn btn-danger btn-block my-3">Back to Portfolio</a>
        </div>
      </div>
    ).html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_home_link.html.erb
<a href="/">Home</a>

app/views/layouts/_logged_in_user_options.html.erb
<ul class="nav justify-content-end">
  <li class="nav-item">
    <%= link_to "Home", root_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Users", users_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Learn Military Ranks", military_rank_tests_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <div class="nav-link disabled">You're logged in!</div>
  </li>
</ul>

app/views/layouts/_social_media_buttons.html.erb
<div class="row socialNav py-3" id="social">
  <div class="col">
    <a class="btn btn-block btn-twitter" href="https://www.twitter.com/independentian" role="button" target="_blank">twitter</a>
  </div>
  <div class="col">
    <a class="btn btn-block btn-facebook" href="https://www.facebook.com/independentian" role="button" target="_blank">facebook</a>
  </div>
  <div class="col">
    <a class="btn btn-block btn-instagram" href="https://www.instagram.com/independentian" role="button" target="_blank">instagram</a>
  </div>
  <div class="col">
    <a class="btn btn-block btn-youtube" href="https://www.youtube.com/user/irobinson1984" role="button" target="_blank">youtube</a>
  </div>
  <div class="col">
    <a class="btn btn-block btn-github" href="https://github.com/iarobinson" role="button" target="_blank">github</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path "big-horn-sheep-icon-red-600.png" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% unless current_user.nil? %>
      <%= render "layouts/logged_in_user_options" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/military_rank_tests/_form.html.erb
<%= form_with(model: military_rank_test, local: true) do |form| %>
  <% if military_rank_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(military_rank_test.errors.count, "error") %> prohibited this military_rank_test from being saved:</h2>

      <ul>
      <% military_rank_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label :branch, "Select Branch to Test For:" %>
    <%= select_tag(:branch, raw(
        '<option value="all">All</option>
        <option value="army">Army</option>
        <option value="navy">Navy</option>
        <option value="air_force">Air Force</option>'
        ), class: "form-control") %>
  </div>

  <div class="actions">
    <%= form.submit "Start the Military Rank Test", class: "btn btn-block btn-primary my-3" %>
  </div>
<% end %>

app/views/military_rank_tests/edit.html.erb
<h1>Editing Military Rank Test</h1>

<%= render 'form', military_rank_test: @military_rank_test %>

<%= link_to 'Show', @military_rank_test %> |
<%= link_to 'Back', military_rank_tests_path %>

app/views/military_rank_tests/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 py-3">
      <p id="notice"><%= notice %></p>
      <%= link_to 'Take the Test', new_military_rank_test_path, class: "btn btn-block btn-primary" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <table class="table">
          <thead>
            <tr>
              <th>Result</th>
              <th>Points</th>
              <th>Date</th>
              <th colspan="3">Manage</th>
            </tr>
          </thead>

          <tbody>
            <% @military_rank_tests.each do |military_rank_test| %>
              <tr>
                <td>
                  <%= military_rank_test.result %>
                </td>
                <td>
                  <%= military_rank_test.points %>
                </td>
                <td>
                  <%= military_rank_test.updated_at %>
                </td>
                <td>
                  <%= link_to 'Show', military_rank_test, class: "btn btn-block btn-primary" %>
                </td>
                <td>
                  <%= link_to 'Edit', edit_military_rank_test_path(military_rank_test), class: "btn btn-block btn-primary" %>
                </td>
                <td>
                  <%= link_to 'Destroy', military_rank_test, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-block btn-primary" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag "military_rank_test/military_rank_test_jr_enlisted.jpg", class: "img-fluid" %>
    </div>
    <div class="col-md-4">
      <%= image_tag "military_rank_test/military_rank_test_sr_enlisted.jpg", class: "img-fluid" %>
    </div>
    <div class="col-md-4">
      <%= image_tag "military_rank_test/military_rank_test_officer.jpg", class: "img-fluid" %>
    </div>
  </div>
</div>

app/views/military_rank_tests/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-3">


      <h1 class="text-center">New Military Rank Test</h1>

      <%= render 'form', military_rank_test: @military_rank_test %>

      <%= link_to 'Back', military_rank_tests_path, class: "btn btn-block btn-primary my-3" %>
    </div>
  </div>
</div>

app/views/military_rank_tests/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Result:</strong>
        <%= @military_rank_test.result %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @military_rank_test.user %>
      </p>

      <p>
        <strong>Points:</strong>
        <%= @military_rank_test.points %>
      </p>

      <%= link_to 'Edit', edit_military_rank_test_path(@military_rank_test), class: "btn btn-block btn-primary" %>
      <%= link_to 'Back', military_rank_tests_path, class: "btn btn-block btn-primary" %>
    </div>
  </div>
</div>

app/views/pages/_external_projects.html.erb
<div class="row">
  <h2>External Links</h2>
</div>
<div class="row">
  <div class="col-md-4 gallery">
    <a href="https://www.freedompodcasting.com" target="_blank">
      <%= image_tag "project_thumbnails/freedom-podcasting.png", class: "img-fluid", alt: "A Professional Podcast Production company" %>
    </a>
    <p>We are a company offering podcast production services to clients since 2011.</p>
  </div>
  <div class="col-md-4 gallery">
    <%= link_to "https://www.ianrobinson.net", target: "_blank" do %>
      <%= image_tag "project_thumbnails/personal-blog.png", class: "img-fluid", alt: "My personal blog - a study of art, enterprise and entrepreneurship." %>
    <% end %>
    <p>My personal blog with wide ranging topics from:</p>
    <p><font size="3"><em>house building, learning to code, book notes, travel ideas, film making, cryptocurrency and much more.</em></font></p>
  </div>
  <div class="col-md-4 gallery">
    <%= link_to "https://www.usefulprogrammer.org", target: "_blank" do %>
      <%= image_tag "project_thumbnails/useful-programmer.jpg", class: "img-fluid", alt: "My personal blog - a study of art, enterprise and entrepreneurship." %>
    <% end %>
    <p>My personal blog with wide ranging topics from:</p>
    <p><font size="3"><em>teaching early stage developers the basics of programatic thinking</em></font></p>
  </div>
</div>

app/views/pages/_logged_in_user_projects.html.erb
<div class="row">
  <h2>Logged In User Projects:</h2>
  <div class="col-12">
    <p><%= link_to "Learn Military Ranks", military_rank_tests_path %></p>
  </div>
</div>

app/views/pages/_project_rows.html.erb
<div class="row">
  <h2>Projects:</h2>
</div>
<div class="row">
  <div class="row centered mt mb">
    <div class="col-md-4 col-sm-4 gallery">
      <%= link_to quick_check_path do %>
        <%= image_tag "project_thumbnails/wikipedia-quick-check-tool.jpg", class: "img-fluid" %>
      <% end %>
      <p>A tool for finding multiple related Wikipedia articles.</p>
    </div>
    <div class="col-md-4 col-sm-4 gallery">
      <%= link_to random_quote_path do %>
        <%= image_tag "project_thumbnails/tweet-generator.jpg", class: "img-fluid" %>
      <% end %>
      <p>A random quote generator for spamming Hack Reactor founders.</p>
    </div>
    <div class="col-md-4 col-sm-4 gallery">
      <%= link_to calculator_path do %>
        <%= image_tag "project_thumbnails/js-calculator.jpg", class: "img-fluid" %>
      <% end %>
      <p>A mobile responsive JavaScript calculator.</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-sm-4 gallery">
    <%= link_to jockoclock_path do %>
      <%= image_tag "project_thumbnails/jocko-clock.jpg", class: "img-fluid", alt: "A clock that gets Jocko Willink to help you stop procrastinating" %>
    <% end %>
    <p>Jocko Clock is a Pomodoro clock which helps you eliminate procrastination featuring the voice of Jocko Willink.</p>
  </div>
  <div class="col-md-4 col-sm-4 gallery">
    <%= link_to heart_path do %>
      <%= image_tag "project_thumbnails/heart.jpg", class: "img-fluid", alt: "A love heart in CSS" %>
    <% end %>
    <p>A throbbing heart.</p>
  </div>
  <div class="col-md-4 col-sm-4 gallery">
    <%= link_to tick_tack_toe_path do %>
      <%= image_tag "project_thumbnails/tic-toc-toe.jpg", class: "img-fluid", alt: "A simple Tic Tac Toe Game" %>
    <% end %>
    <p>This is just a simple game of Tic Tac Toe written in JavaScript, HTML and CSS.</p>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-sm-4 gallery">
    <%= link_to roulette_wheel_consecutive_count_path do %>
      <%= image_tag "project_thumbnails/roulette-wheel-spinner-project.jpg", class: "img-fluid", alt: "A roulette wheel statistics project" %>
    <% end %>
    <p>A project where we explore the number of consecutive results in a roulette wheel spin.</p>
  </div>
</div>

app/views/pages/calculator.html.erb
<script>
  $(document).ready(function() {
    $(".btn").on("click", function() {
      var buttonPressed = $(this).html();
      runTheNumbers(buttonPressed);
    });
  });
  var stringyNum = '', previousNum = '', operand = '';
  var numbers = '1234567890'.split('');
  var operandSelected = ['add', 'subtract', 'multiply', 'divide'];

  function updateDisplay(stringyNum) {
    $('th#display').replaceWith('<th colspan="4" id="display"><p align="right">' + stringyNum.substring(0, 10) + '</p></th>');
  }

  function runTheNumbers(buttonPressed) {

    if (isNum(buttonPressed)) {
      stringyNum += buttonPressed;
      updateDisplay(stringyNum);
    } else if (buttonPressed === 'clear') {
      stringyNum = '';
      previousNum = '';
      operand = '';
      updateDisplay("0");
    } else if (buttonPressed === '.' && decimalOK()) {
      stringyNum += buttonPressed;
      updateDisplay(stringyNum);
    } else if (isOperand(buttonPressed)) {
      if (previousNum === '') {
        prepCalc(buttonPressed);
        updateDisplay(previousNum);
      } else {
        previousNum = runCalc();
        stringyNum = '';
        operand = buttonPressed;
        updateDisplay(previousNum);
      }
    } else if (buttonPressed === 'equals') {
      stringyNum = runCalc();
      previousNum = '';
      operand = '';
      updateDisplay(stringyNum);
    } else {
      updateDisplay(stringyNum);
    }
  }

  function runCalc() {
    var result;
    if (operand === 'add') {
      result = parseFloat(previousNum) + parseFloat(stringyNum);
      return result.toString();
    } else if (operand === 'subtract') {
      result = parseFloat(previousNum) - parseFloat(stringyNum);
      return result.toString();
    } else if (operand === 'multiply') {
      result = parseFloat(previousNum) * parseFloat(stringyNum);
      return result.toString();
    } else if (operand === 'divide') {
      result = parseFloat(previousNum) / parseFloat(stringyNum);
      return result.toString();
    } else {
      return previousNum;
    }
  }

  function prepCalc(op) {
    previousNum = stringyNum;
    stringyNum = '';
    operand = op;
  }

  function isOperand(buttonPressed) {
    return operandSelected.indexOf(buttonPressed) !== -1
  }

  function isNum(buttonPressed) {
    return numbers.indexOf(buttonPressed) > -1
  }

  function decimalOK() {
    return stringyNum.indexOf('.') === -1
  }
</script>
<div class="container-fluid">
  <%= raw return_home_button %>
  <div class="row mt-5">
    <div class="col-md-8 offset-md-2">
      <table class="table table-borderless">
        <th colspan="4" id="display">
          <center>
            <p>Display</p>
          </center>
        </th>
        <tr>
          <th scope="col"><button type="button" class="btn btn-primary btn-block">1</button></th>
          <th scope="col"><button type="button" class="btn btn-primary btn-block">2</button></th>
          <th scope="col"><button type="button" class="btn btn-primary btn-block">3</button></th>
          <th scope="col"><button type="button" class="btn btn-primary btn-block">add</button></th>
        </tr>
        <tr>
          <th><button type="button" class="btn btn-primary btn-block">4</button></th>
          <th><button type="button" class="btn btn-primary btn-block">5</button></th>
          <th><button type="button" class="btn btn-primary btn-block">6</button></th>
          <th><button type="button" class="btn btn-primary btn-block">subtract</button></th>
        </tr>
        <tr>
          <th><button type="button" class="btn btn-primary btn-block">7</button></th>
          <th><button type="button" class="btn btn-primary btn-block">8</button></th>
          <th><button type="button" class="btn btn-primary btn-block">9</button></th>
          <th><button type="button" class="btn btn-primary btn-block">multiply</button></th>
        </tr>
        <tr>
          <th colspan="2"><button type="button" class="btn btn-primary btn-block">0</button></th>
          <th><button type="button" class="btn btn-primary btn-block">.</button></th>
          <th><button type="button" class="btn btn-primary btn-block">divide</button></th>
        </tr>
        <tr>
          <th colspan="3"><button type="button" class="btn btn-primary btn-block">clear</button></th>
          <th ><button type="button" class="btn btn-primary btn-block">equals</button></th>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/pages/heart.html.erb
<style>
  .back {
    position: fixed;
    padding: 0;
    margin: 0;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: white;
    animation-name: backdiv;
    animation-duration: 2s;
    animation-iteration-count: infinite;
  }

  .heart {
    position: absolute;
    margin: auto;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: red;
    height: 100px;
    width: 100px;
    transform: rotate(-45deg);
    animation-name: throb;
    animation-duration: 2s;
    animation-iteration-count: infinite;
  }
  .heart:after {
    background-color: red;
    content: "";
    border-radius: 50%;
    position: absolute;
    width: 100px;
    height: 100px;
    top: 0px;
    left: 50px;
  }
  .heart:before {
    content: "";
    background-color: red;
    border-radius: 50%;
    position: absolute;
    width: 100px;
    height: 100px;
    top: -50px;
    left: 0px;
  }
  @keyframes throb {
    0% {
      transform: scale(1) rotate(-45deg);
    } 50% {
      transform: scale(0.9) rotate(-45deg);
    }
  }

  @keyframes backdiv {
    0% {
      opacity: .5;
    } 50% {
      background-color: #ffe6f2;
    }
  }
</style>

<div class="back"></div>
<div class="heart"></div>
<%= return_home_button %>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h2 class="text-center">
        <%= image_tag "ian.jpeg", width: "50px" %>
        Hi, I'm Ian.
      </h2>
    </div>
    <div class="col-8 offset-2">
      <p>This is my portfolio web app.</p>
      <p>This is a collection of my favorite projects.
        These were created over the past few years of learning to code.
      </p>
      <% if current_user.nil? %>
        <p>
          Some projects work better for users who login in. If you want to see those projects, please
          <%= link_to "sign in", new_user_session_path %> or
          <%= link_to "sign up", new_user_registration_path %>.
        </p>
      <% end %>
      <p>Please check out the thumbnails below to explore my work.</p>
    </div>
  </div>


  <% unless current_user.nil? %>
    <%= render "pages/logged_in_user_projects" %>
  <% end %>
  <%= render "pages/project_rows" %>
  <%= render "pages/external_projects" %>
  <%= render "layouts/social_media_buttons" %>
</div>

app/views/pages/jockoclock.html.erb
<script>
  // Find the day to display on watch
  var d = new Date()
  var days = "SUN MON TUE WED THR FRI SAT".split(' ');
  var day = days[d.getDay()];

  // The default number of seconds on clock
  var secondsToGo = 1500;

  // Happens when reset clock button is clicked
  function resetClock() {
    if (secondsToGo === -1) {
      location.reload();
    }
    secondsToGo = 1500;
  }

  function setCustomMinutes() {
    if (secondsToGo === -1) {
      location.reload();
    }
    var desiredTime = parseInt(document.getElementById("newTime").value) * 60;
    secondsToGo = desiredTime;
  }

  // Displays 00 rather than 01 for seconds and 04 seconds rather than 4
  function displaySeconds(seconds) {
    var sparSeconds = seconds % 60;

    if (sparSeconds === 0) {
      return '00';
    } else if (sparSeconds < 10) {
      return '0' + seconds % 60;
    } else {
      return sparSeconds;
    }
  }

  $(document).ready(function() {

    // Clock Operation and Display
    var runTime = setInterval(function() {
      // Renders time to watch display
      document.getElementById("timeDisplay").innerHTML = day + "    " + Math.floor((secondsToGo / 60)) + ":" + displaySeconds(secondsToGo);

      // Decrements the time to go
      secondsToGo -= 1;

      // What to do when the minutes have counted down
      if (secondsToGo < 0) {
        // Comment this out to avoid listening to the audio too much while programming

        document.getElementById("warpath").play();
        document.getElementById("timeDisplay").innerHTML = "<p id='expired'>EXPIRED<p>";
        document.getElementById("dayDisplay").innerHTML = '';
        clearInterval(runTime);
      }
    }, 1000);
  });
</script>

<div class="bg">

  <%= return_home_button %>
  <div class="center align-middle">
    <p id="timeDisplay">Get. After. It.</p>
    <p id="dayDisplay"></p>
    <form>
      <input type="number" id="newTime" min="1" max="500" >
      <input type="button" value="Start Custom Minutes" onclick="setCustomMinutes()">
      <input type="button" value="Reset Clock" onClick="resetClock()">
    </form>
  </div>
</div>

app/views/pages/scratch.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6 offset-3 pt-4">
      <h1>Scratch Page!</h1>
      <%= link_to "Go Home!", root_path, class: "btn btn-primary btn-block" %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.string %></td>
        <td><%= question.string %></td>
        <td><%= question.string %></td>
        <td><%= question.string %></td>
        <td><%= question.string %></td>
        <td><%= question.string %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @question.string %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>